apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.210.149.40"],"port":32194,"protocol":"TCP","serviceName":"wrx:go-web-hello-world","allNodes":true}]'
  creationTimestamp: "2019-12-27T09:05:11Z"
  generation: 2
  labels:
    run: go-web-hello-world
  name: go-web-hello-world
  namespace: wrx
  resourceVersion: "12255883"
  selfLink: /apis/extensions/v1beta1/namespaces/wrx/deployments/go-web-hello-world
  uid: fcffe0a5-2887-11ea-b2a8-005056010e91
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: go-web-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: go-web-hello-world
    spec:
      containers:
      - image: armdocker.rnd.ericsson.se/sandbox/go-web-hello-world:wrx-0.0.1
        imagePullPolicy: IfNotPresent
        name: go-web-hello-world
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-12-27T09:05:14Z"
    lastUpdateTime: "2019-12-27T09:05:14Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-12-27T09:05:11Z"
    lastUpdateTime: "2019-12-27T09:05:14Z"
    message: ReplicaSet "go-web-hello-world-595d4f4fdc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
